# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Pixel Art Site
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  KuraHonyo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Navigation settings
navigation:
  - name: "Home"
    link: "/"
  - name: "About"
    link: "/about"
  - name: "Portfolio"
    link: "/portfolio"
  - name: "Commission Info"
    link: "/commission-info"
  - name: "Order Form"
    link: "/order-form"
  - name: "Shop"
    link: "/shop"
  - name: "Blog/News"
    link: "/blog"
  - name: "Contact"
    link: "/contact"
  - name: "Testimonials"
    link: "/testimonials"
  - name: "FAQ"
    link: "/faq"
  - name: "Privacy Policy"
    link: "/privacy-policy"
  - name: "Terms and Conditions"
    link: "/terms-and-conditions"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Header and Footer Links (if using a custom theme that supports these)
header_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Portfolio"
    url: "/portfolio"
  - title: "Commission Info"
    url: "/commission-info"
  - title: "Order Form"
    url: "/order-form"
  - title: "Shop"
    url: "/shop"
  - title: "Blog/News"
    url: "/blog"
  - title: "Contact"
    url: "/contact"
  - title: "Testimonials"
    url: "/testimonials"
  - title: "FAQ"
    url: "/faq"
  - title: "Privacy Policy"
    url: "/privacy-policy"
  - title: "Terms and Conditions"
    url: "/terms-and-conditions"

footer_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Portfolio"
    url: "/portfolio"
  - title: "Commission Info"
    url: "/commission-info"
  - title: "Order Form"
    url: "/order-form"
  - title: "Shop"
    url: "/shop"
  - title: "Blog/News"
    url: "/blog"
  - title: "Contact"
    url: "/contact"
  - title: "Testimonials"
    url: "/testimonials"
  - title: "FAQ"
    url: "/faq"
  - title: "Privacy Policy"
    url: "/privacy-policy"
  - title: "Terms and Conditions"
    url: "/terms-and-conditions"
